### ISSUE TITLE
No document

### ISSUE THREAD

**Issue by SolarisYan** [monzo/egress-operator#5]
Hi there, is there a detailed usage document? I read the current documentation but don't know how to use

**Comment by jackkleeman** [comment]
There isn't I'm afraid. I'll think about writing one. Essentially you need to deploy this operator using the kustomize manifests in `config/default`, and deploy the coreDNS image to your kubedns deployment, and then write ExternalService CRDs

**Comment by jackkleeman** [comment]
I've added some improved docs @SolarisYan

**Comment by SolarisYan** [comment]
@jackkleeman Thanks a lot
